name: Consulta Cliente

on:
  repository_dispatch:
    types: [consulta_cliente]

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Notificacion
        run: echo "Consulta de cliente realizada. Notificacion del Equipo de AXA."

        
      
