name: Consultar Cliente

on:
  repository_dispatch:
    types: [consulta_cliente]

jobs:
  consultar:
    runs-on: ubuntu-latest
    steps:
      - name: Notificación de consulta
        run: echo "Consulta de cliente realizada. Notificación del equipo de AXA."