name: Crear Cliente

on:
  push:
    paths:
      - "clientes/**"

jobs:
  crear:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar creación de archivo
        run: |
          if git diff --name-status HEAD~1 HEAD | grep "^A"; then
            echo "Cliente creado. Notificación del equipo de AXA."
          else
            echo "No hubo creación de cliente. Workflow finalizado sin error."
          fi