name: Crear Cliente

on:
  push:
    branches: ["main"]
    paths:
      - "clientes/**"

jobs:
  detectar_creacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detectar creación de archivo
        run: |
          if git diff --name-status HEAD~1 HEAD | grep "^A"; then
            echo "Cliente creado"
          else
            echo "No hubo creación"
            exit 1
          fi

      - name: Notificacion
        run: echo "Se ha creado un nuevo cliente. Notificación del equipo de AXA."