name: Modificar Cliente

on:
  push:
    paths:
      - "clientes/**"

jobs:
  modificar:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar modificación de archivo
        run: |
          if git diff --name-status HEAD~1 HEAD | grep "^M"; then
            echo "Cliente modificado. Notificación del equipo de AXA."
          else
            echo "No hubo modificación de cliente. Workflow finalizado sin error."
          fi